#pragma once

#define FAT_BAD_DESC 0xFFu8

#define FAT_OK 0u8
#define FAT_ERROR_NO_CARD 1u8
#define FAT_ERROR_UNSUPPORTED_FAT_TYPE 2u8
#define FAT_ERROR_UNSUPPORTED_SECTOR_SIZE 3u8
#define FAT_ERROR_TOO_MANY_FATS 4u8
#define FAT_ERROR_TOO_MANY_OPEN_FILES 5u8
#define FAT_ERROR_NOT_A_DIR 6u8
#define FAT_ERROR_CARD_REINSERTED 7u8
#define FAT_ERROR_CARD 8u8
#define FAT_ERROR_FS_BROKEN 9u8
#define FAT_ERROR_NOT_FOUND 10u8
#define FAT_ERROR_BAD_DESCRIPTOR 11u8
#define FAT_EOF 12u8
#define FAT_ERROR_RELATIVE_PATH 13u8
#define FAT_ERROR_IS_DIR 14u8
#define FAT_ERROR_STALE_DESCRIPTOR 15u8
